[build]
command = "npm run build"
publish = "dist"
functions = "functions"
publish = "."

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/chatbot"
to = "/.netlify/functions/chatbot"
status = 200